# -*- coding: utf-8 -*-
"""FINAL_FL_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFdY9PKjsbRtl5unsxG2ZEBzQ9KuMg0V
"""

import torch
import numpy as np
import random

SEED = 42

torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# ---- Proper CICIDS Reload with Class Separation ----

import zipfile
import os
import pandas as pd

ZIP_PATH = "/content/CICIDS2017.zip"
EXTRACT_DIR = "/content/cicids_fixed"

# Extract again (safe even if already extracted)
with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_DIR)

csv_files = [os.path.join(EXTRACT_DIR, f)
             for f in os.listdir(EXTRACT_DIR)
             if f.endswith(".csv")]

print("CSV files found:", len(csv_files))

benign_list = []
attack_list = []

for f in csv_files:
    df_temp = pd.read_csv(f)

    # Identify label column
    label_col = [c for c in df_temp.columns if "category" in c.lower()][0]

    # Separate classes
    benign = df_temp[df_temp[label_col] == 0]
    attack = df_temp[df_temp[label_col] != 0]

    benign_list.append(benign)
    attack_list.append(attack)

# Combine all benign and attack samples
benign_df = pd.concat(benign_list, ignore_index=True)
attack_df = pd.concat(attack_list, ignore_index=True)

print("Total benign:", len(benign_df))
print("Total attack:", len(attack_df))

# ---- Create Balanced Dataset ----

min_class_size = min(len(benign_df), len(attack_df))

benign_sampled = benign_df.sample(min_class_size, random_state=42)
attack_sampled = attack_df.sample(min_class_size, random_state=42)

balanced_df = pd.concat([benign_sampled, attack_sampled])
balanced_df = balanced_df.sample(frac=1, random_state=42)  # shuffle

print("Balanced dataset size:", balanced_df.shape)
print(balanced_df["Attempted Category"].apply(lambda x: 0 if x==0 else 1).value_counts())

import numpy as np

# Create binary label
balanced_df["binary_label"] = balanced_df["Attempted Category"].apply(
    lambda x: 0 if x == 0 else 1
)

# Drop non-feature columns
drop_cols = ["Attempted Category", "Flow ID"]
drop_cols += [c for c in balanced_df.columns if c.startswith("Local")]

balanced_df = balanced_df.drop(columns=drop_cols)

# Remove inf and NaN
balanced_df = balanced_df.replace([np.inf, -np.inf], np.nan)
balanced_df = balanced_df.dropna()

# Final X and y
X = balanced_df.drop(columns=["binary_label"]).values
y = balanced_df["binary_label"].values

print("Final X shape:", X.shape)
print("Final y distribution:", np.bincount(y))

# Keep only numeric columns
balanced_df = balanced_df.select_dtypes(include=['number'])

print("Remaining columns:", balanced_df.shape[1])

X = balanced_df.drop(columns=["binary_label"]).values
y = balanced_df["binary_label"].values

print("New X shape:", X.shape)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

import numpy as np

NUM_CLIENTS = 5

client_data = []

split_size = len(X_train) // NUM_CLIENTS

for i in range(NUM_CLIENTS):
    start = i * split_size
    end = (i + 1) * split_size
    client_data.append(
        (X_train[start:end], y_train[start:end])
    )

print("Clients created:", len(client_data))

import torch
import torch.nn as nn
import torch.optim as optim

class FLModel(nn.Module):
    def __init__(self, input_dim):
        super(FLModel, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 2)
        )

    def forward(self, x):
        return self.model(x)

import torch

# Convert test set to torch tensors
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# Convert client data to tensors
client_tensors = []

for X_c, y_c in client_data:
    X_c = torch.tensor(X_c, dtype=torch.float32)
    y_c = torch.tensor(y_c, dtype=torch.long)
    client_tensors.append((X_c, y_c))

print("Client tensor preparation complete")

def local_train(model, X, y, epochs=2, lr=0.01):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr)

    model.train()

    for _ in range(epochs):
        optimizer.zero_grad()
        outputs = model(X)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()

    return model.state_dict()

def fedavg(global_model, client_states):
    global_dict = global_model.state_dict()

    for key in global_dict.keys():
        global_dict[key] = torch.stack(
            [client_state[key] for client_state in client_states],
            dim=0
        ).mean(dim=0)

    global_model.load_state_dict(global_dict)
    return global_model

NUM_ROUNDS = 20
input_dim = X_train.shape[1]

global_model = FLModel(input_dim)

accuracy_per_round = []

for round_num in range(NUM_ROUNDS):

    client_states = []

    # Send model to each client
    for X_c, y_c in client_tensors:
        local_model = FLModel(input_dim)
        local_model.load_state_dict(global_model.state_dict())

        updated_state = local_train(local_model, X_c, y_c)
        client_states.append(updated_state)

    # Aggregate
    global_model = fedavg(global_model, client_states)

    # Evaluate
    global_model.eval()
    with torch.no_grad():
        outputs = global_model(X_test_tensor)
        _, preds = torch.max(outputs, 1)
        acc = (preds == y_test_tensor).float().mean().item()

    accuracy_per_round.append(acc)

    print(f"Round {round_num+1} - Global Accuracy: {acc:.4f}")
iid_model = FLModel(input_dim)
iid_model.load_state_dict(global_model.state_dict())

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1),
         accuracy_per_round,
         linewidth=2)

plt.xlabel("Federated Rounds", fontsize=12)
plt.ylabel("Global Accuracy", fontsize=12)
plt.title("Convergence of FedAvg (IID Clients)", fontsize=13)

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Separate train data by class
X_train_np = X_train
y_train_np = y_train

benign_idx = np.where(y_train_np == 0)[0]
attack_idx = np.where(y_train_np == 1)[0]

print("Total benign in train:", len(benign_idx))
print("Total attack in train:", len(attack_idx))

NUM_CLIENTS = 5

skew_config = [
    (0.9, 0.1),  # Client 1
    (0.1, 0.9),  # Client 2
    (0.7, 0.3),  # Client 3
    (0.3, 0.7),  # Client 4
    (0.5, 0.5)   # Client 5
]

client_data_noniid = []

total_per_client = len(X_train_np) // NUM_CLIENTS

for i in range(NUM_CLIENTS):

    benign_ratio, attack_ratio = skew_config[i]

    num_benign = int(total_per_client * benign_ratio)
    num_attack = total_per_client - num_benign

    selected_benign = np.random.choice(benign_idx, num_benign, replace=False)
    selected_attack = np.random.choice(attack_idx, num_attack, replace=False)

    selected_indices = np.concatenate([selected_benign, selected_attack])
    np.random.shuffle(selected_indices)

    X_c = torch.tensor(X_train_np[selected_indices], dtype=torch.float32)
    y_c = torch.tensor(y_train_np[selected_indices], dtype=torch.long)

    client_data_noniid.append((X_c, y_c))

print("Non-IID clients created:", len(client_data_noniid))

accuracy_noniid = []

NUM_ROUNDS = 20
input_dim = X_train.shape[1]

global_model = FLModel(input_dim)

for round_num in range(NUM_ROUNDS):

    client_states = []

    for X_c, y_c in client_data_noniid:

        local_model = FLModel(input_dim)
        local_model.load_state_dict(global_model.state_dict())

        updated_state = local_train(local_model, X_c, y_c)
        client_states.append(updated_state)

    global_model = fedavg(global_model, client_states)

    global_model.eval()
    with torch.no_grad():
        outputs = global_model(X_test_tensor)
        _, preds = torch.max(outputs, 1)
        acc = (preds == y_test_tensor).float().mean().item()

    accuracy_noniid.append(acc)   # 🔥 THIS LINE IS CRITICAL

    print(f"Round {round_num+1} - Global Accuracy: {acc:.4f}")
noniid_model = FLModel(input_dim)
noniid_model.load_state_dict(global_model.state_dict())

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1),
         accuracy_noniid,
         linewidth=2)

plt.xlabel("Federated Rounds", fontsize=12)
plt.ylabel("Global Accuracy", fontsize=12)
plt.title("Convergence of FedAvg (IID Clients)", fontsize=13)

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print(type(accuracy_noniid))
print(accuracy_noniid)

NUM_BYZANTINE = 2

def generate_random_weights(model):
    random_state = {}
    for key, value in model.state_dict().items():
        random_state[key] = torch.randn_like(value)
    return random_state

accuracy_byzantine = []

NUM_ROUNDS = 20
input_dim = X_train.shape[1]

global_model = FLModel(input_dim)

for round_num in range(NUM_ROUNDS):

    client_states = []

    for i, (X_c, y_c) in enumerate(client_data_noniid):

        # If client is Byzantine
        if i < NUM_BYZANTINE:
            malicious_state = generate_random_weights(global_model)
            client_states.append(malicious_state)

        else:
            local_model = FLModel(input_dim)
            local_model.load_state_dict(global_model.state_dict())

            updated_state = local_train(local_model, X_c, y_c)
            client_states.append(updated_state)

    # Aggregate
    global_model = fedavg(global_model, client_states)

    # Evaluate
    global_model.eval()
    with torch.no_grad():
        outputs = global_model(X_test_tensor)
        _, preds = torch.max(outputs, 1)
        acc = (preds == y_test_tensor).float().mean().item()

    accuracy_byzantine.append(acc)

    print(f"Round {round_num+1} - Global Accuracy: {acc:.4f}")
byz_model = FLModel(input_dim)
byz_model.load_state_dict(global_model.state_dict())

print(type(accuracy_byzantine))
print(accuracy_byzantine)

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1),
         accuracy_byzantine,
         linewidth=2)

plt.xlabel("Federated Rounds", fontsize=12)
plt.ylabel("Global Accuracy", fontsize=12)
plt.title("Convergence of FedAvg (Byzantine Clients)", fontsize=13)

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1), accuracy_per_round, label="IID")
plt.plot(range(1, NUM_ROUNDS+1), accuracy_noniid, label="Non-IID")
plt.plot(range(1, NUM_ROUNDS+1), accuracy_byzantine, label="Non-IID + Byzantine")

plt.xlabel("Federated Rounds")
plt.ylabel("Global Accuracy")
plt.title("Effect of Non-IID and Byzantine Clients")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

def fed_median(global_model, client_states):
    global_dict = global_model.state_dict()

    for key in global_dict.keys():

        # Stack client weights for this layer
        stacked = torch.stack(
            [client_state[key] for client_state in client_states],
            dim=0
        )

        # Compute median across clients
        global_dict[key] = torch.median(stacked, dim=0).values

    global_model.load_state_dict(global_dict)
    return global_model

accuracy_median = []

NUM_ROUNDS = 20
input_dim = X_train.shape[1]

global_model = FLModel(input_dim)

for round_num in range(NUM_ROUNDS):

    client_states = []

    for i, (X_c, y_c) in enumerate(client_data_noniid):

        # Byzantine clients
        if i < NUM_BYZANTINE:
            malicious_state = generate_random_weights(global_model)
            client_states.append(malicious_state)
        else:
            local_model = FLModel(input_dim)
            local_model.load_state_dict(global_model.state_dict())

            updated_state = local_train(local_model, X_c, y_c)
            client_states.append(updated_state)

    # 🔥 Use Median instead of FedAvg
    global_model = fed_median(global_model, client_states)

    # Evaluate
    global_model.eval()
    with torch.no_grad():
        outputs = global_model(X_test_tensor)
        _, preds = torch.max(outputs, 1)
        acc = (preds == y_test_tensor).float().mean().item()

    accuracy_median.append(acc)

    print(f"Round {round_num+1} - Global Accuracy: {acc:.4f}")
median_model = FLModel(input_dim)
median_model.load_state_dict(global_model.state_dict())

plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1), accuracy_byzantine, label="FedAvg + Byzantine")
plt.plot(range(1, NUM_ROUNDS+1), accuracy_median, label="Median Aggregation")

plt.xlabel("Federated Rounds")
plt.ylabel("Global Accuracy")
plt.title("Robust Aggregation under Byzantine Attack")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1),
         accuracy_median,
         linewidth=2)

plt.xlabel("Federated Rounds", fontsize=12)
plt.ylabel("Global Accuracy", fontsize=12)
plt.title("Convergence of FedAvg (Median aggregation)", fontsize=13)

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

def flatten_model(state_dict):
    return torch.cat([v.flatten() for v in state_dict.values()])

import torch.nn.functional as F

def compute_trust_scores_median_based(client_states):

    flattened = [flatten_model(cs) for cs in client_states]
    stacked = torch.stack(flattened)

    # Compute global median vector
    median_vector = torch.median(stacked, dim=0).values

    distances = torch.zeros(len(flattened))

    for i in range(len(flattened)):
        distances[i] = torch.norm(flattened[i] - median_vector, p=2)

    # Smaller distance → higher trust
    trust_scores = 1 / (distances + 1e-8)
    trust_scores = trust_scores / trust_scores.sum()

    return trust_scores

def fed_trust_median(global_model, client_states):

    global_dict = global_model.state_dict()
    trust_scores = compute_trust_scores_median_based(client_states)

    for key in global_dict.keys():

        stacked = torch.stack(
            [client_state[key] for client_state in client_states],
            dim=0
        )

        weighted_sum = torch.zeros_like(global_dict[key])

        for i in range(len(client_states)):
            weighted_sum += trust_scores[i] * stacked[i]

        global_dict[key] = weighted_sum

    global_model.load_state_dict(global_dict)
    return global_model

accuracy_trust = []

NUM_ROUNDS = 20
input_dim = X_train.shape[1]

global_model = FLModel(input_dim)

for round_num in range(NUM_ROUNDS):

    client_states = []

    for i, (X_c, y_c) in enumerate(client_data_noniid):

        if i < NUM_BYZANTINE:
            malicious_state = generate_random_weights(global_model)
            client_states.append(malicious_state)
        else:
            local_model = FLModel(input_dim)
            local_model.load_state_dict(global_model.state_dict())

            updated_state = local_train(local_model, X_c, y_c)
            client_states.append(updated_state)

    # 🔥 Trust aggregation
    global_model = fed_trust(global_model, client_states)

    # Evaluate
    global_model.eval()
    with torch.no_grad():
        outputs = global_model(X_test_tensor)
        _, preds = torch.max(outputs, 1)
        acc = (preds == y_test_tensor).float().mean().item()

    accuracy_trust.append(acc)

    print(f"Round {round_num+1} - Global Accuracy: {acc:.4f}")
trust_model = FLModel(input_dim)
trust_model.load_state_dict(global_model.state_dict())

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))

plt.plot(range(1, NUM_ROUNDS+1),
         accuracy_trust,
         linewidth=2)

plt.xlabel("Federated Rounds", fontsize=12)
plt.ylabel("Global Accuracy", fontsize=12)
plt.title("Convergence of FedAvg (Byzantine Clients)", fontsize=13)

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model, X_test_tensor, y_test_tensor):

    model.eval()
    with torch.no_grad():
        outputs = model(X_test_tensor)
        _, preds = torch.max(outputs, 1)

    y_true = y_test_tensor.cpu().numpy()
    y_pred = preds.cpu().numpy()

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    return acc, prec, rec, f1

results = {}

results["IID"] = evaluate_model(iid_model, X_test_tensor, y_test_tensor)
results["Non-IID"] = evaluate_model(noniid_model, X_test_tensor, y_test_tensor)
results["Byzantine (FedAvg)"] = evaluate_model(byz_model, X_test_tensor, y_test_tensor)
results["Median"] = evaluate_model(median_model, X_test_tensor, y_test_tensor)
results["Trust-Median"] = evaluate_model(trust_model, X_test_tensor, y_test_tensor)

for key, value in results.items():
    print(f"{key}:")
    print(f" Accuracy: {value[0]:.4f}")
    print(f" Precision: {value[1]:.4f}")
    print(f" Recall: {value[2]:.4f}")
    print(f" F1 Score: {value[3]:.4f}")
    print()

def convergence_stable(accuracy_list, threshold=0.005, patience=3):

    for i in range(len(accuracy_list) - patience):

        stable = True

        for j in range(patience):
            diff = abs(accuracy_list[i + j + 1] - accuracy_list[i + j])

            if diff > threshold:
                stable = False
                break

        if stable:
            return i + 1   # round number

    return len(accuracy_list)

print("IID Convergence:", convergence_stable(accuracy_per_round))
print("Non-IID Convergence:", convergence_stable(accuracy_noniid))
print("Byzantine Convergence:", convergence_stable(accuracy_byzantine))
print("Median Convergence:", convergence_stable(accuracy_median))
print("Trust Convergence:", convergence_stable(accuracy_trust))

attack_tolerance_median = results["Median"][0] / results["Non-IID"][0]
attack_tolerance_trust = results["Trust-Median"][0] / results["Non-IID"][0]

print("Median Attack Tolerance:", attack_tolerance_median)
print("Trust Attack Tolerance:", attack_tolerance_trust)

import pandas as pd

df_results = pd.DataFrame(results,
                          index=["Accuracy", "Precision", "Recall", "F1"]).T

df_results

import matplotlib.pyplot as plt

# Methods
methods = ["IID", "Non-IID", "Byzantine (FedAvg)", "Median", "Trust-Median"]

# Final Metrics
accuracy = [0.7296, 0.5085, 0.4701, 0.8431, 0.8351]
f1_scores = [0.6652, 0.6621, 0.5889, 0.8154, 0.8528]

# ----------------------------
# Accuracy Bar Graph
# ----------------------------
plt.figure(figsize=(8,5))
plt.bar(methods, accuracy)
plt.xlabel("Method")
plt.ylabel("Accuracy")
plt.title("Final Accuracy Comparison")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("accuracy_comparison.png", dpi=300)
plt.show()


# ----------------------------
# F1 Score Bar Graph
# ----------------------------
plt.figure(figsize=(8,5))
plt.bar(methods, f1_scores)
plt.xlabel("Method")
plt.ylabel("F1 Score")
plt.title("Final F1 Score Comparison")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("f1_comparison.png", dpi=300)
plt.show()

methods = ["IID", "Non-IID", "Byzantine", "Median", "Trust-Median"]
convergence_rounds = [14, 3, 20, 20, 20]

plt.figure()
plt.bar(methods, convergence_rounds)
plt.xlabel("Method")
plt.ylabel("Convergence Round")
plt.title("Convergence Round Comparison")
plt.xticks(rotation=45)
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import torch

trust_model.eval()
with torch.no_grad():
    outputs = trust_model(X_test_tensor)
    _, preds = torch.max(outputs, 1)

cm = confusion_matrix(y_test_tensor.cpu(), preds.cpu())

plt.figure()
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Confusion Matrix - Trust-Median")
plt.show()

baseline_acc = 0.5085  # Non-IID final accuracy

improvement = [acc - baseline_acc for acc in accuracy_trust]

rounds = range(1, len(accuracy_trust) + 1)

plt.figure()
plt.plot(rounds, improvement)
plt.xlabel("Communication Rounds")
plt.ylabel("Accuracy Improvement over Non-IID")
plt.title("Rounds vs Performance Improvement (Trust-Median)")
plt.show()

median_acc = 0.8431
trust_acc = 0.8351
baseline_acc = 0.5085

attack_tolerance_median = ((median_acc - baseline_acc) / baseline_acc) * 100
attack_tolerance_trust = ((trust_acc - baseline_acc) / baseline_acc) * 100

methods = ["Median", "Trust-Median"]
tolerance_values = [attack_tolerance_median, attack_tolerance_trust]

plt.figure()
plt.bar(methods, tolerance_values)
plt.xlabel("Method")
plt.ylabel("Improvement Percentage (%)")
plt.title("Attack Tolerance Improvement over Non-IID")
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score
import torch
import matplotlib.pyplot as plt
import numpy as np

trust_model.eval()

with torch.no_grad():
    outputs = trust_model(X_test_tensor)

    # Convert logits to probabilities
    probabilities = torch.softmax(outputs, dim=1)[:, 1]  # positive class prob

y_true = y_test_tensor.cpu().numpy()
y_scores = probabilities.cpu().numpy()

precision, recall, thresholds = precision_recall_curve(y_true, y_scores)
avg_precision = average_precision_score(y_true, y_scores)

plt.figure()
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve (Trust-Median)")
plt.show()

print("Average Precision (AP):", avg_precision)

plt.figure()
plt.plot(recall_trust, precision_trust)
plt.plot(recall_median, precision_median)
plt.plot(recall_byz, precision_byz)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve Comparison")
plt.legend(["Trust-Median", "Median", "Byzantine FedAvg"])
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score
import torch

def get_pr_curve(model, X_test_tensor, y_test_tensor):

    model.eval()
    with torch.no_grad():
        outputs = model(X_test_tensor)
        probs = torch.softmax(outputs, dim=1)[:, 1]

    y_true = y_test_tensor.cpu().numpy()
    y_scores = probs.cpu().numpy()

    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    avg_precision = average_precision_score(y_true, y_scores)

    return precision, recall, avg_precision

precision_trust, recall_trust, ap_trust = get_pr_curve(trust_model, X_test_tensor, y_test_tensor)

precision_median, recall_median, ap_median = get_pr_curve(median_model, X_test_tensor, y_test_tensor)

precision_byz, recall_byz, ap_byz = get_pr_curve(byz_model, X_test_tensor, y_test_tensor)

import matplotlib.pyplot as plt

plt.figure()

plt.plot(recall_trust, precision_trust)
plt.plot(recall_median, precision_median)
plt.plot(recall_byz, precision_byz)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve Comparison")
plt.legend([
    f"Trust-Median (AP={ap_trust:.3f})",
    f"Median (AP={ap_median:.3f})",
    f"Byzantine FedAvg (AP={ap_byz:.3f})"
])

plt.show()

